[package]
name = "match_each"
version = "0.1.0-dev"
authors = ["Jonas Jebing <noreply.jonas.8049@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
